const packs = [
  { name: "Deemo's collection Vol.1", image: "pack_image/Deemo's collection Vol.1.png"},
  { name: "Vocal collection", image: "pack_image/Vocal collection.png"},
  { name: "Deemo's collection Vol.2", image: "pack_image/Deemo's collection Vol.2.png"},
  { name: "Golden Sheets Collection", image: "pack_image/Golden Sheets Collection.png"},
  { name: "Reborn Collection", image: "pack_image/Reborn Collection.png"},
  { name: "Stone Monument Collection", image: "pack_image/Stone Monument Collection.png"},
  { name: "Aioi Collection", image: "pack_image/Aioi Collection.png" },
  { name: "Cytus Selection vol.1", image: "pack_image/Cytus Selection vol.1.webp" },
  { name: "Cytus Selection vol.2", image: "pack_image/Cytus Selection vol.2.png" },
  { name: "EGOIST Special Selection", image: "pack_image/EGOIST Special Selection.webp" },
  { name: "Knight Iris Collection", image: "pack_image/Knight Iris Collection.webp" },
  { name: "MILI collection", image: "pack_image/MILI collection.webp" },
  { name: "N.M.S.T. Collection", image: "pack_image/N.M.S.T. Collection.png" },
  { name: "Rayark Selection vol.3", image: "pack_image/Rayark Selection vol.3.png" }
];

const songs = [
  {  title: "Dream",  artist: "Rabpit",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 1, Normal: 3, Hard: 6 }},
  {  title: "Jumpy star",  artist: "Yuk-cheung Chun / Jeff Li / Justine Lu",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 3, Normal: 4, Hard: 7 }},
  {  title: "Nine point eight",  artist: "Mili",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 2, Normal: 5, Hard: 7 }},
  {  title: "Run Go Run",  artist: "Kaeru Underground",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 1, Normal: 5, Hard: 8 }},
  {  title: "YUBIKIRI-GENMAN",  artist: "Mili",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 2, Normal: 4, Hard: 8 }},
  {  title: "Walking by the sea",  artist: "Edmund Fu",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 3, Normal: 6, Hard: 8 }},
  {  title: "Entrance",  artist: "Ice",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 4, Normal: 7, Hard: 10 }},
  {  title: "Magnolia",  artist: "M2U",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 4, Normal: 7, Hard: 10 }},
  {  title: "彩華",  artist: "Rabpit",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 1, Normal: 5, Hard: 8 }},
  {  title: "Beyond The Stratus",  artist: "Ice",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 2, Normal: 4, Hard: 6 }},
  {  title: "Light pollution",  artist: "Yuk-cheung Chun feat. Europa Huang",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 3, Normal: 6, Hard: 8 }},
  {  title: "Utopiosphere",  artist: "Mili",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 2, Normal: 5, Hard: 9 }},
  {  title: "Angelic Sphere",  artist: "3R2",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 3, Normal: 4, Hard: 6 }},
  {  title: "Electron",  artist: "Yuk-cheung Chun feat. Misi Ke",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 2, Normal: 6, Hard: 8 }},
  {  title: "Untitled2",  artist: "Fabric Factory",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 3, Normal: 4, Hard: 7 }},
  {  title: "Undo",  artist: "Yuk-cheung Chun feat. Misi Ke",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 1, Normal: 3, Hard: 6 }},
  {  title: "I hate to tell you",  artist: "Yuk-cheung Chun",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 2, Normal: 4, Hard: 8 }},
  {  title: "Platinum",  artist: "Sta",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 1, Normal: 4, Hard: 6 }},
  {  title: "Leviathan",  artist: "NeLiME",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 4, Normal: 7, Hard: 9 }},
  {  title: "Invite",  artist: "Sun Chen feat. Bibi Chao",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 3, Normal: 5, Hard: 8 }},
  {  title: "Pulses",  artist: "Sta",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 1, Normal: 5, Hard: 8 }},
  {  title: "SAIRAI",  artist: "Shinichi Kobayashi",  pack: "Deemo's collection Vol.1",  difficulties: { Easy: 2, Normal: 5, Hard: 9 }},
  {  title: "Pharmacy of heart",  artist: "white tail box ft.riri",  pack: "Vocal collection",  difficulties: { Easy: 2, Normal: 4, Hard: 6 }},
  {  title: "Aurarobe",  artist: "onoken feat.Rin",  pack: "Vocal collection",  difficulties: { Easy: 3, Normal: 5, Hard: 8 }},
  {  title: "Red Storm Sentiment",  artist: "Tsukasa feat. Kalon",  pack: "Vocal collection",  difficulties: { Easy: 3, Normal: 7, Hard: 9 }},
  {  title: "Ukakuf Kins",  artist: "t+pazolite feat. Nanahira",  pack: "Vocal collection",  difficulties: { Easy: 3, Normal: 6, Hard: 9 }},
  {  title: "Faith, Hope & Love",  artist: "Iris ft.Victor Kong & LynH",  pack: "Vocal collection",  difficulties: { Easy: 2, Normal: 6, Hard: 8 }},
  {  title: "Vandarhythm",  artist: "Apo11o program ft.Ritsuka",  pack: "Vocal collection",  difficulties: { Easy: 1, Normal: 4, Hard: 6 }},
  {  title: "Re:you ～彼の地を知りえたとして～",  artist: "Apo11o program &ゆゆうた ft. OFFICE萬田㈱",  pack: "Vocal collection",  difficulties: { Easy: 2, Normal: 7, Hard: 9 }},
  {  title: "Chance",  artist: "Silaver",  pack: "Vocal collection",  difficulties: { Easy: 4, Normal: 8, Hard: 10 }},
  {  title: "My Dear,Deemo",  artist: "Iris ft.LynH",  pack: "Vocal collection",  difficulties: { Easy: 3, Normal: 6, Hard: 9 }},
  {  title: "Suspenseful Third Day",  artist: "Kaeru Underground",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 3, Normal: 5, Hard: 8 }},
  {  title: "Legacy",  artist: "switchworks",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 2, Normal: 4, Hard: 7 }},
  {  title: "Myosotis",  artist: "M2U / Arranger: M2U & NICODE / Vocal: Guriri & Lucy",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 5, Normal: 9, Hard: 11 }},
  {  title: "ANiMA",  artist: "xi",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 5, Normal: 9, Hard: 10 }},
  {  title: "Fluquor",  artist: "onoken / Vocal: Rin",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 3, Normal: 6, Hard: 8 }},
  {  title: "Living In The One",  artist: "Edmund Fu",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 3, Normal: 6, Hard: 7 }},
  {  title: "La Promesse",  artist: "Cranky",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 2, Normal: 5, Hard: 8 }},
  {  title: "The Beautiful Moonlight",  artist: "Mai Aoyagi",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 3, Normal: 5, Hard: 7 }},
  {  title: "Sunset",  artist: "Alex Vourtsanis",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 2, Normal: 5, Hard: 9 }},
  {  title: "Ark of Desire",  artist: "Edmund Fu",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 4, Normal: 6, Hard: 9 }},
  {  title: "Starting Wind",  artist: "Edmund Fu",  pack: "Deemo's collection Vol.2",  difficulties: { Easy: 4, Normal: 7, Hard: 9 }},
  {  title: "Nier Fluquor",  artist: "onoken",  pack: "Golden Sheets Collection",  difficulties: { Easy: 2, Normal: 6, Hard: 8 }},
  {  title: "まよいづき",  artist: "onoken feat.実咲",  pack: "Golden Sheets Collection",  difficulties: { Easy: 3, Normal: 5, Hard: 7 }},
  {  title: "Prélude de l'adieu",  artist: "onoken",  pack: "Golden Sheets Collection",  difficulties: { Easy: 3, Normal: 6, Hard: 8 }},
  {  title: "あいたい",  artist: "onoken feat.Rin",  pack: "Golden Sheets Collection",  difficulties: { Easy: 5, Normal: 7, Hard: 10 }},
  {  title: "Für Alice",  artist: "onoken",  pack: "Golden Sheets Collection",  difficulties: { Easy: 4, Normal: 6, Hard: 8 }},
  {  title: "Mirai",  artist: "onoken feat.b",  pack: "Golden Sheets Collection",  difficulties: { Easy: 3, Normal: 6, Hard: 9 }},
  {  title: "Me",  artist: "Laur",  pack: "Reborn Collection",  difficulties: { Easy: 3, Normal: 6, Hard: 8 }},
  {  title: "Blue evenfall",  artist: "Freeleaves",  pack: "Reborn Collection",  difficulties: { Easy: 3, Normal: 7, Hard: 9 }},
  {  title: "Dawn of the ruins",  artist: "Freeleaves",  pack: "Reborn Collection",  difficulties: { Easy: 3, Normal: 6, Hard: 9 }},
  {  title: "The Last Bloom",  artist: "3R2",  pack: "Reborn Collection",  difficulties: { Easy: 1, Normal: 5, Hard: 7 }},
  {  title: "Code:11",  artist: "KIVΛ",  pack: "Reborn Collection",  difficulties: { Easy: 3, Normal: 6, Hard: 8 }},
  {  title: "Delphinium",  artist: "SIHanatsuka",  pack: "Reborn Collection",  difficulties: { Easy: 1, Normal: 4, Hard: 7 }},
  {  title: "Accelerando",  artist: "計畫通行",  pack: "Reborn Collection",  difficulties: { Easy: 4, Normal: 8, Hard: 10 }},
  {  title: "Tempestuous",  artist: "計畫通行",  pack: "Reborn Collection",  difficulties: { Easy: 5, Normal: 8, Hard: 10 }},
  {  title: "Exodus",  artist: "Iris",  pack: "Reborn Collection",  difficulties: { Easy: 5, Normal: 7, Hard: 9 }},
  {  title: "eterno",  artist: "Takashi OKAMOTO(12sound) feat.Tsukasa Shiraki",  pack: "Reborn Collection",  difficulties: { Easy: 4, Normal: 6, Hard: 8 }},
  {  title: "Liar",  artist: "Takashi OKAMOTO(12sound)",  pack: "Reborn Collection",  difficulties: { Easy: 3, Normal: 5, Hard: 7 }},
  {  title: "Squeaky Mind",  artist: "t+pazolite",  pack: "Reborn Collection",  difficulties: { Easy: 3, Normal: 7, Hard: 10 }},
  {  title: "Place Your Bets",  artist: "3R2",  pack: "Reborn Collection",  difficulties: { Easy: 4, Normal: 7, Hard: 9 }},
  {  title: "Etude",  artist: "MIDInco",  pack: "Stone Monument Collection",  difficulties: { Easy: 6, Normal: 9, Hard: 10 }},
  {  title: "迅雷天響",  artist: "柳田Ethnica",  pack: "Stone Monument Collection",  difficulties: { Easy: 6, Normal: 9, Hard: 10 }},
  {  title: "Creation of Fighters",  artist: "Art of fighters vs.Apo11o program +DD“ナカタ”Metal",  pack: "Stone Monument Collection",  difficulties: { Easy: 6, Normal: 9, Hard: 10 }},
  {  title: "Intersteller Exploration",  artist: "spacebot(floating)",  pack: "Stone Monument Collection",  difficulties: { Easy: 6, Normal: 9, Hard: 10 }},
  {  title: "saihate",  artist: "Apo11o “QUASAR”program ft.遠藤駿",  pack: "Stone Monument Collection",  difficulties: { Easy: 6, Normal: 9, Hard: 10 }},

  { pack: "Cytus Selection vol.1", title: "DRG", artist: "Ani", difficulties: { Easy: 4, Normal: 7, Hard: 9 } },
  { pack: "Cytus Selection vol.1", title: "Libera me", artist: "Cranky", difficulties: { Easy: 3, Normal: 8, Hard: 10 } },
  { pack: "Cytus Selection vol.1", title: "Precipitation", artist: "Ice", difficulties: { Easy: 5, Normal: 7, Hard: 10 } },
  { pack: "Cytus Selection vol.1", title: "Sacred", artist: "Rabpit", difficulties: { Easy: 3, Normal: 5, Hard: 9 } },
  { pack: "Cytus Selection vol.1", title: "The Black Case", artist: "KillerBlood", difficulties: { Easy: 3, Normal: 5, Hard: 7 } },

  { pack: "MILI collection", title: "Fable", artist: "Mili", difficulties: { Easy: 5, Normal: 7, Hard: 9 } },
  { pack: "MILI collection", title: "Past the Stargazing Season", artist: "H△G / Remixed by Mili", difficulties: { Easy: 3, Normal: 6, Hard: 8 } },
  { pack: "MILI collection", title: "Ephemeral", artist: "Mili", difficulties: { Easy: 3, Normal: 5, Hard: 8 } },
  { pack: "MILI collection", title: "Rosetta", artist: "Mili", difficulties: { Easy: 4, Normal: 7, Hard: 9 } },
  { pack: "MILI collection", title: "Witch's Invitation", artist: "Mili", difficulties: { Easy: 3, Normal: 7, Hard: 9 } },

  { pack: "Cytus Selection vol.2", title: "Future World", artist: "Killerblood", difficulties: { Easy: 4, Normal: 6, Hard: 8 } },
  { pack: "Cytus Selection vol.2", title: "Holy Knight", artist: "Eyemedia", difficulties: { Easy: 3, Normal: 7, Hard: 10 } },
  { pack: "Cytus Selection vol.2", title: "Niflheimr", artist: "xi", difficulties: { Easy: 2, Normal: 7, Hard: 10 } },
  { pack: "Cytus Selection vol.2", title: "Parousia", artist: "xi", difficulties: { Easy: 4, Normal: 8, Hard: 10 } },
  { pack: "Cytus Selection vol.2", title: "Recollections", artist: "Yamajet", difficulties: { Easy: 3, Normal: 7, Hard: 9 } },

  { pack: "N.M.S.T. Collection", title: "Farewell", artist: "3R2", difficulties: { Easy: 1, Normal: 4, Hard: 6 } },
  { pack: "N.M.S.T. Collection", title: "Winter", artist: "3R2", difficulties: { Easy: 3, Normal: 5, Hard: 7 } },
  { pack: "N.M.S.T. Collection", title: "Fluffie Partie", artist: "N.M.S.T.", difficulties: { Easy: 3, Normal: 6, Hard: 8 } },
  { pack: "N.M.S.T. Collection", title: "Snowflakes", artist: "N.M.S.T.", difficulties: { Easy: 3, Normal: 7, Hard: 9 } },
  { pack: "N.M.S.T. Collection", title: "kouyou", artist: "Ice", difficulties: { Easy: 6, Normal: 9, Hard: 10 } },

  { pack: "Aioi Collection", title: "CREAM STEW (Deemo Ver.)", artist: "aioi feat. KAMATA JUNKO", difficulties: { Easy: 3, Normal: 6, Hard: 9 } },
  { pack: "Aioi Collection", title: "I can not say (Deemo Ver.)", artist: "aioi feat. KAMATA JUNKO", difficulties: { Easy: 3, Normal: 5, Hard: 6 } },
  { pack: "Aioi Collection", title: "Image (Deemo Ver.)", artist: "aioi feat. KAMATA JUNKO", difficulties: { Easy: 2, Normal: 5, Hard: 7 } },
  { pack: "Aioi Collection", title: "kireigoto (Deemo Ver.)", artist: "aioi feat. KAMATA JUNKO", difficulties: { Easy: 2, Normal: 5, Hard: 7 } },
  { pack: "Aioi Collection", title: "NEW WORLD (Deemo Ver.)", artist: "aioi feat. KAMATA JUNKO", difficulties: { Easy: 4, Normal: 6, Hard: 8 } },

  { pack: "Rayark Selection vol.3", title: "Little Corgi's Dream", artist: "KillerBlood", difficulties: { Easy: 2, Normal: 5, Hard: 7 } },
  { pack: "Rayark Selection vol.3", title: "Morning Drops", artist: "KIVA", difficulties: { Easy: 3, Normal: 5, Hard: 8 } },
  { pack: "Rayark Selection vol.3", title: "The Letter", artist: "KIVA", difficulties: { Easy: 4, Normal: 6, Hard: 7 } },
  { pack: "Rayark Selection vol.3", title: "Waltz in Devil's Playground", artist: "Ramenbot Jr.", difficulties: { Easy: 3, Normal: 6, Hard: 9 } },
  { pack: "Rayark Selection vol.3", title: "Veritas", artist: "Presti", difficulties: { Easy: 3, Normal: 7, Hard: 10 } },

  { pack: "Knight Iris Collection", title: "The Way We Were", artist: "NICODE", difficulties: { Easy: 4, Normal: 6, Hard: 8 } },
  { pack: "Knight Iris Collection", title: "The Sanctuary", artist: "Eye AC", difficulties: { Easy: 3, Normal: 5, Hard: 7 } },
  { pack: "Knight Iris Collection", title: "The Red Coronation", artist: "Eye RH", difficulties: { Easy: 2, Normal: 6, Hard: 9 } },
  { pack: "Knight Iris Collection", title: "Forbidden Codex", artist: "Hoskey", difficulties: { Easy: 3, Normal: 6, Hard: 10 } },
  { pack: "Knight Iris Collection", title: "Knight of Firmament", artist: "Eye XY", difficulties: { Easy: 2, Normal: 7, Hard: 8 } },

  { pack: "EGOIST Special Selection", title: "All Alone With You", artist: "EGOIST", difficulties: { Easy: 3, Normal: 5, Hard: 8 } },
  { pack: "EGOIST Special Selection", title: "Planetes", artist: "EGOIST", difficulties: { Easy: 1, Normal: 3, Hard: 7 } },
  { pack: "EGOIST Special Selection", title: "キミソラキセキ", artist: "EGOIST", difficulties: { Easy: 2, Normal: 4, Hard: 7 } },
  { pack: "EGOIST Special Selection", title: "Ghost of a smile", artist: "EGOIST", difficulties: { Easy: 1, Normal: 3, Hard: 6 } },
  { pack: "EGOIST Special Selection", title: "Departures ～あなたにおくるアイの歌～", artist: "EGOIST", difficulties: { Easy: 2, Normal: 5, Hard: 7 } }
];
